name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List PersistenceAPI workflows
        id: list-workflows
        shell: bash
        run: |
          {
            echo "workflows<<EOF"
            curl -L --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H 'Accept: application/vnd.github+json; charset=utf-8' 'https://api.github.com/repos/0x5abe/PersistenceAPI/actions/runs?per_page=1&status=success'
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
  
      - name: Fetch PersistenceAPI
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: 0x5abe/PersistenceAPI
          run-id: ${{ fromJSON(steps.list-workflows.outputs.workflows).workflow_runs[0].id }}

      - name: Extract in geode-deps
        shell: bash
        run: |
          mkdir -p build/geode-deps/sabe.persistenceapi
          7z x './Build Output/sabe.persistenceapi.geode' '-o./build/geode-deps/sabe.persistenceapi'
          echo '{ "required": true }' > build/geode-deps/sabe.persistenceapi/geode-dep-options.json

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          combine: true
          cli: "latest"
          sdk: "nightly"
          export-pdb: true
          build-config: RelWithDebInfo

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: build/*.geode
